web:
    image: registry.cn-hangzhou.aliyuncs.com/web_nginx_php7/alpine:upgrade
    ports:
      - "80:80"
    links:
      - redis:redis_instance
      - mongodb:mongo_instance
    volumes:
      - /home/test/web/logs/:/log
      - /home/test/web/www:/var/www/html
      - /home/test/web/nginx_config:/etc/nginx/sites-available
      
redis:
    image: redis:alpine
    volumes:
      - /home/test/web/data/:/data

mongodb:
    image: mongo
